AWSTemplateFormatVersion: 2010-09-09
Description: Fargate service for dex exchange

Resources:
  #Creating Tasks
  Exchange:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: exchange-service
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: service3
          Image: public.ecr.aws/w2z5i4h0/dex-exchange-service:v3
          Cpu: 256
          Memory: 512
          PortMappings:
            - ContainerPort: 9000
              Protocol: tcp
  Service:
    Type: AWS::ECS::Service
    DependsOn: LoadBalancerRule
    Properties:
      ServiceName: exchange-service
      TaskDefinition: !Ref Exchange
      Cluster: !ImportValue "Dex-LK"
      LaunchType: FARGATE
      DesiredCount: 1
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 70
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !ImportValue dex-PublicSubnet1
            - !ImportValue dex-PublicSubnet2
          SecurityGroups:
            - !Ref ExchangeSecurityGroup
      LoadBalancers:
        - ContainerName: service3
          ContainerPort: 9000
          TargetGroupArn: !Ref TargetGroup
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: exchange-tg
      VpcId: !ImportValue dex-VPC
      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 60
      HealthCheckPath: /api/exchange-funds/health-check
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 30
      HealthyThresholdCount: 10
      TargetType: ip
      Tags:
        - Key: Name
          Value: exchange-tg
  ExchangeSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable http(9000) & ssh(22) access
      GroupName: Exchange-SG
      VpcId: !ImportValue dex-VPC
      SecurityGroupIngress:
        # allow http
        - IpProtocol: tcp
          FromPort: "9000"
          ToPort: "9000"
          CidrIp: 0.0.0.0/0 # any IP
      Tags:
        - Key: Name
          Value: Exchange SG
  LoadBalancerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: "forward"
      Conditions:
        - Field: path-pattern
          Values:
            - /api/exchange*
      ListenerArn: arn:aws:elasticloadbalancing:ap-southeast-1:524642062901:listener/app/ALB/0813910c7dc18f93/e99cc5b435cf533f
      Priority: 25
